server {
    listen 8080;
    server_name localhost;

    add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://lh3.googleusercontent.com; connect-src 'self'; media-src 'self'; font-src 'self' data:" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;

    location /music/training/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /music/training/index.html;
    }

    location /music/training/assets/ {
        root /usr/share/nginx/html;
    }
}
